version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tdes
      MYSQL_USER: tdes
      MYSQL_PASSWORD: Meiyoumima;
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-backend
    container_name: spring-boot-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/tdes?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT+8
      SPRING_DATASOURCE_USERNAME: tdes
      SPRING_DATASOURCE_PASSWORD: Meiyoumima;
      # 根据需要添加更多的环境变量
    depends_on:
      - mariadb

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-frontend
    container_name: vue-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  mariadb_data:
  letsencrypt:
