FROM node:lts-alpine as build-stage
WORKDIR /app
COPY ./tdes-frontend/package*.json ./
RUN npm install
COPY ./tdes-frontend/ .
RUN npm run build

FROM nginx:stable-alpine as production-stage

# SSL certificate
RUN apk add --no-cache certbot certbot-nginx


COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY ../docker/default.conf /etc/nginx/conf.d/default.conf

COPY ../entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


EXPOSE 80 443

ENTRYPOINT ["/entrypoint.sh"]
